

<form name="mahasiswa" id="mahasiswa" method="post" action="">
<table clas="table">
<tr><th>Nama Mahasiswa</th><td>:</td>
<td><input type="text" size="30" name="namamhs" id="namamhs" value="<?php echo $this->mahasiswa[0]['NAMA']?>">
</td></tr>
<tr><th>NIM</th><td>:</td>
<td><input type="text" size="12" name="nimmhs" id="nimmhs" value="<?php echo $this->mahasiswa[0]['NIM']?>">
 <tr><th>Alamat</th><td>:</td><td><input type="text" size="12" name="alamatmhs" id="alamatmhs" value="<?php echo $this->mahasiswa[0]['ALAMAT']?>">
</td></tr>
<tr><th>Sex</th><td>:</td>
<td><input type="text" size="30" name="sexmhs" id="sexmhs" value="<?php echo $this->mahasiswa[0]['SEX']?>">
</td></tr>
<tr><th>Program Studi</th><td>:</td>
<td><input type="text" size="30" name="prodimhs" id="prodimhs" value="<?php echo $this->mahasiswa[0]['PRODI']?>">
</td></tr>
<tr><th>Agama</th><td>:</td>
<td><input type="text" size="30" name="agamamhs" id="agamamhs" value="<?php echo $this->mahasiswa[0]['AGAMA']?>">
</td></tr>
<tr><th>Angkatan</th><td>:</td>
<td><input type="text" size="30" name="angkatanmhs" id="angkatanmhs" value="<?php echo $this->mahasiswa[0]['ANGKATAN']?>">
</td></tr>
<tr><th></th><td></td><td>
<input type="text" name="idmhs" value="<?php  echo $this->mahasiswa[0]['Idmhs']?>">
<input type="submit" name="Search" value="Search">
<input type="submit" name="Save" value="Save">
<input type="submit" name="delete" value="Delete">
</td></tr>
</table>

</form>

<table class="table" >
<tr><th>NIM</th><th>Nama</th><th>Alamat</th></tr>
<?php if ($this->biodatas!=array()) {
foreach ($this->biodatas as $bio) {?>
<tr><td><?php echo $bio['NIM']?></td>
<td><?php echo $bio['NAMA']?></td>
<td><?php echo $bio['ALAMAT']?></td>
<td><?php echo $bio['SEX']?></td>
<td><?php echo $bio['PRODI']?></td>
<td><?php echo $bio['AGAMA']?></td>
<td><?php echo $bio['ANGKATAN']?></td>
</tr>
<?php }
}?>
</table>

//test123